version: '3.9'

services:
  smartschool-web:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile-dev
    container_name: web
    restart: always
    env_file:
      - envs/.env_web_dev
    volumes:
      - ../../backend:/app
      - static:/app/static
      - media:/app/media
      - ../../frontend:/frontend
      - ../../frontend/static:/app/frontend/static
    ports:
      - "8000:8000"
    depends_on:
      smartschool-db:
        condition: service_healthy
    command: sh -c "/entrypoint.sh"

  smartschool-db:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile-db-dev
    image: postgres:16-alpine
    container_name: smartschool-db
    restart: always
    env_file:
      - envs/.env_db_dev
    ports:
      - "7778:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]
    volumes:
      - smartschool_db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  smartschool_db_data:
  static:
  media: