version: '3.8'

services:
  web:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile-dev
    container_name: web
    restart: always
    env_file:
      - envs/.env_web_dev
    volumes:
      - ../../backend:/app
      - static:/app/static
      - media:/app/media
    ports:
      - "7777:8000"
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py runserver

  db:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile-db-dev
    image: postgres:15.2-alpine
    container_name: db
    restart: always
    env_file:
      - envs/.env_db_dev
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static:
  media: