# Generated by Django 5.0.2 on 2024-04-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ManyToManyField(null=True, related_name='users', to='school.school'),
        ),
    ]
