# Generated by Django 5.0.2 on 2024-04-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='leave',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reason_leave',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
