# Generated by Django 5.0.2 on 2024-04-07 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0004_alter_student_leave_alter_student_reason_leave"),
        ("authorization", "0004_user_date_joined"),
    ]

    operations = []
