# Generated by Django 5.0.2 on 2024-04-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_user_school'),
        ('authorization', '0004_user_date_joined'),
    ]

    operations = [
    ]
