# Generated by Django 5.0.2 on 2024-04-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0005_merge_20240407_1621"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_days",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
