# Generated by Django 5.0.2 on 2024-04-07 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_merge_0003_user_school_0004_user_date_joined'),
        ('authorization', '0006_user_login_days'),
    ]

    operations = [
    ]
