# Generated by Django 5.0.2 on 2024-04-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_merge_20240407_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_studying',
            field=models.BooleanField(default=False),
        ),
    ]
