# Generated by Django 5.0.2 on 2024-05-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_alter_student_stud_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Employee', 'Сотрудник'), ('Parent', 'Родитель'), ('Student', 'Ученик'), ('Teacher', 'Учитель')], default='Employee', max_length=20),
        ),
    ]
