# Generated by Django 5.0.2 on 2024-05-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AddField(
            model_name='subjectsection',
            name='cabinet',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectsection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
