# Generated by Django 5.0.2 on 2024-05-07 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_alter_user_role'),
        ('school', '0002_alter_subject_options_subjectsection_cabinet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionaction',
            name='status',
            field=models.CharField(choices=[('Attended', 'Посещено'), ('Absent', 'Отсутствие'), ('Permitted', 'Разрешено'), ('Late', 'Опоздание'), ('Left', 'Покинул занятие')], default='Attended', max_length=155),
        ),
        migrations.CreateModel(
            name='SectionHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='homework/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subjectsection')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'db_table': 'section_homework',
            },
        ),
        migrations.CreateModel(
            name='SectionHomeworkAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='homework/answers/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.sectionhomework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.student')),
            ],
            options={
                'verbose_name': 'Ответ на домашнее задание',
                'verbose_name_plural': 'Ответы на домашние задания',
                'db_table': 'section_homework_answer',
            },
        ),
        migrations.CreateModel(
            name='SectionHomeworkGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.sectionhomework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.student')),
            ],
            options={
                'verbose_name': 'Оценка домашнего задания',
                'verbose_name_plural': 'Оценки домашних заданий',
                'db_table': 'section_homework_grade',
            },
        ),
    ]
