# Generated by Django 5.0.2 on 2024-05-07 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_alter_user_role'),
        ('school', '0003_alter_sectionaction_status_sectionhomework_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='tests/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subjectsection')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'db_table': 'section_tests',
            },
        ),
        migrations.CreateModel(
            name='SectionTestsAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='tests/answers/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.sectiontests')),
            ],
            options={
                'verbose_name': 'Ответ на тест',
                'verbose_name_plural': 'Ответы на тесты',
                'db_table': 'section_tests_answer',
            },
        ),
        migrations.CreateModel(
            name='SectionTestsGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.sectiontests')),
            ],
            options={
                'verbose_name': 'Оценка теста',
                'verbose_name_plural': 'Оценки тестов',
                'db_table': 'section_tests_grade',
            },
        ),
    ]
