# Generated by Django 5.0.2 on 2024-06-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_sectiontests_sectiontestsanswer_sectiontestsgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='short_name',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
