# Generated by Django 5.0.2 on 2024-04-22 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='contract_date_close',
            new_name='date_close',
        ),
    ]
