# Generated by Django 5.0.2 on 2024-04-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_rename_contract_date_contract_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(default='Cash', max_length=255),
        ),
    ]
