# Generated by Django 5.0.2 on 2024-04-29 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0004_transaction_payment_type"),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="school",
            field=models.ForeignKey(
                db_column="school",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="school.school",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="contract",
            field=models.ForeignKey(
                db_column="contract",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="contract.contract",
            ),
        ),
    ]
