# Generated by Django 5.0.2 on 2024-05-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_alter_contract_school_alter_transaction_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_close',
            field=models.DateField(blank=True, null=True),
        ),
    ]
