# Generated by Django 5.0.2 on 2024-05-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_alter_contract_date_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_type',
            field=models.CharField(choices=[('Monthly', 'Ежемесячно'), ('Quarterly', 'Ежеквартально'), ('Annual', 'Ежегодно')], default='Monthly', max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Formed', 'Сформирован'), ('Consideration', 'На рассмотрении'), ('Signed', 'Подписан'), ('Finished', 'Завершен'), ('Canceled', 'Отменен'), ('Dissolved', 'Расторгнут')], default='Formed', max_length=255),
        ),
    ]
